using Microsoft.Playwright;
using NUnit.Framework;
using System.Threading.Tasks;


namespace PlaywrightBeginner
{
    public class Tests
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public async Task Test1()
        {
            //playwright download browsers
            using var playwright = await Playwright.CreateAsync(); //this will help download things from the internet,downloads the driver behind the scene
                                                                   //Browser of choice and then use it
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false, //meaning not running the code in headless mode //this will help the browser to launch open
            });
            //As you can see from above, all async calls will Async attached to the name
            //Next is to launch the page as seen in the architecture from my study notes
            //To override the headless value which is set as true, we need to use the key 'new BrowserTypeLaunchOptions' so the browser can launch open
            var page = await browser.NewPageAsync();
            //we are not using 'using' in the above because we want to use the var across all the methods
            await page.GotoAsync(url: "http://www.eaapp.somee.com");
            // await page.PauseAsync(); //this helps to inspect the locators
            //The above takes us to site-URL we want to work on.
            await page.ClickAsync(selector: "text=Login");
            //after it takes to the above url, you want to perform a click operation by calling the click method,
            //then it clicks the login on the page, note the spelling too on here and on the page
            await page.ScreenshotAsync(new PageScreenshotOptions
            {
                Path = "EAApp.jpg"
            }
            );
            //the above helps you to see the browser when it launch, more like implicit wait/thread.sleep and it saves the
            //...screenshot to the Path as EAApp.jpg
            //To access the screenshot, go to the directory>bin>debug>EAApp jpg file

            //await page.FillAsync(selector: "#UserName", value: "admin");
            // await page.FillAsync(selector: "#Password", value: "password");
            await page.GetByRole(AriaRole.Textbox, new() { Name = "User Name" }).FillAsync("admin");
            await page.GetByRole(AriaRole.Textbox, new() { Name = "Password" }).FillAsync("password");
            // var usernameValue = await page.InputValueAsync("#UserName");
            //Console.WriteLine($"Username entered: {usernameValue}");
            //await page.PauseAsync(); //used this to get the locator generated by playwright
            //await page.ClickAsync(selector: "text=Sign In");
            await page.GetByRole(AriaRole.Button, new() { Name = "Sign In" }).ClickAsync(); ;
            //FillAsync is equi to EnterTextToInputField in selenium in my login page where the argument are username and password
            await page.ScreenshotAsync(new() { Path = "AfterLogin.jpg" });
            //await page.PauseAsync();
            //var isExist = await page.Locator(selector: "text=Details").IsVisibleAsync();
            var isExist = await page.GetByRole(AriaRole.Button, new() { Name = "Logout" }).IsVisibleAsync();
            //await page.PauseAsync();
            //Locator method returns an element locator that can be used to perform actions on a page, the locator is used to resolve element imediately
            //...before performing an action..a series of action locator can be done on the different DOM elements
            //isvisible is same as displayed in selenium
            Assert.IsTrue(isExist);
            //this is the assertion to confirm that we are login into the userhomepage
        }
    }
}
