using FluentAssertions;
using Microsoft.Playwright;
using Microsoft.VisualBasic;
using NUnit.Framework;
using PlaywrightBeginner.Application_Layer.Pages;
using System;
using System.Threading.Tasks;
using System.Web;


namespace PlaywrightBeginner
{
    public class Tests
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public async Task Test1()
        {
            //playwright download browsers
            using var playwright = await Playwright.CreateAsync(); //this will help download things from the internet,downloads the driver behind the scene
                                                                   //Browser of choice and then use it
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false, //meaning not running the code in headless mode //this will help the browser to launch open
            });
            //As you can see from above, all async calls will Async attached to the name
            //Next is to launch the page as seen in the architecture from my study notes
            //To override the headless value which is set as true, we need to use the key 'new BrowserTypeLaunchOptions' so the browser can launch open
            var page = await browser.NewPageAsync();
            //we are not using 'using' in the above because we want to use the var across all the methods
            await page.GotoAsync(url: "http://www.eaapp.somee.com");
            // await page.PauseAsync(); //this helps to inspect the locators
            //The above takes us to site-URL we want to work on.
            await page.ClickAsync(selector: "text=Login");
            //after it takes to the above url, you want to perform a click operation by calling the click method,
            //then it clicks the login on the page, note the spelling too on here and on the page
            await page.ScreenshotAsync(new PageScreenshotOptions
            {
                Path = "EAApp.jpg"
            }
            );
            //the above helps you to see the browser when it launch, more like implicit wait/thread.sleep and it saves the
            //...screenshot to the Path as EAApp.jpg
            //To access the screenshot, go to the directory>bin>debug>EAApp jpg file

            //await page.FillAsync(selector: "#UserName", value: "admin");
            // await page.FillAsync(selector: "#Password", value: "password");
            await page.GetByRole(AriaRole.Textbox, new() { Name = "User Name" }).FillAsync("admin");
            await page.GetByRole(AriaRole.Textbox, new() { Name = "Password" }).FillAsync("password");
            // var usernameValue = await page.InputValueAsync("#UserName");
            //Console.WriteLine($"Username entered: {usernameValue}");
            //await page.PauseAsync(); //used this to get the locator generated by playwright
            //await page.ClickAsync(selector: "text=Sign In");
            await page.GetByRole(AriaRole.Button, new() { Name = "Sign In" }).ClickAsync();
            //FillAsync is equi to EnterTextToInputField in selenium in my login page where the argument are username and password
            await page.ScreenshotAsync(new() { Path = "AfterLogin.jpg" });
            //await page.PauseAsync();
            //var isExist = await page.Locator(selector: "text=Details").IsVisibleAsync();
            var isExist = await page.GetByRole(AriaRole.Button, new() { Name = "Logout" }).IsVisibleAsync();
            //await page.PauseAsync();
            //Locator method returns an element locator that can be used to perform actions on a page, the locator is used to resolve element imediately
            //...before performing an action..a series of action locator can be done on the different DOM elements
            //isvisible is same as displayed in selenium
            Assert.IsTrue(isExist);
            //this is the assertion to confirm that we are login into the userhomepage


            //Locators
            /*var login = page.Locator(selector: "text=Login");
            await login.ClickAsync();*/
        }
        [Test]
        public async Task TestPOM()
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false,
            });
            var page = await browser.NewPageAsync();
            await page.GotoAsync(url: "http://www.eaapp.somee.com");
            LoginPage loginPage = new LoginPage(page);
            await loginPage.ClickLogin();
            await loginPage.Login("admin", "password");
            /* await page.ClickAsync(selector: "text=Login");
             await page.ScreenshotAsync(new PageScreenshotOptions
             {
                 Path = "EAApp.jpg"
             }
            );

             await page.GetByRole(AriaRole.Textbox, new() { Name = "User Name" }).FillAsync("admin");
             await page.GetByRole(AriaRole.Textbox, new() { Name = "Password" }).FillAsync("password");
             await page.GetByRole(AriaRole.Button, new() { Name = "Sign In" }).ClickAsync();
             await page.ScreenshotAsync(new() { Path = "AfterLogin.jpg" });*/
            //var isExist = await page.GetByRole(AriaRole.Button, new() { Name = "Logout" }).IsVisibleAsync();
            var isExist = await loginPage.IsLogoutTabDisplayed();
            Assert.IsTrue(isExist);
        }

        [Test]
        public async Task TestPOMUpgraded()
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false,
            });
            var page = await browser.NewPageAsync();
            await page.GotoAsync(url: "http://www.eaapp.somee.com");
            var loginPage = new LoginPageUpgraded(page);
            await loginPage.ClickLogin();
            await loginPage.Login("admin", "password");
            /* await page.ClickAsync(selector: "text=Login");
             await page.ScreenshotAsync(new PageScreenshotOptions
             {
                 Path = "EAApp.jpg"
             }
            );

             await page.GetByRole(AriaRole.Textbox, new() { Name = "User Name" }).FillAsync("admin");
             await page.GetByRole(AriaRole.Textbox, new() { Name = "Password" }).FillAsync("password");
             await page.GetByRole(AriaRole.Button, new() { Name = "Sign In" }).ClickAsync();
             await page.ScreenshotAsync(new() { Path = "AfterLogin.jpg" });*/
            //var isExist = await page.GetByRole(AriaRole.Button, new() { Name = "Logout" }).IsVisibleAsync();
            var isExist = await loginPage.IsLogoutTabDisplayed();
            Assert.IsTrue(isExist);
        }

        [Test]
        public async Task WaitTest()
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false,
            });
            var context = await browser.NewContextAsync();
            var page = await context.NewPageAsync();
            await page.GotoAsync(url: "https://demos.telerik.com/kendo-ui/window/angular");
            //await page.PauseAsync();
            await page.Locator(selector: "text=calendar May 2022SuMoTuWeThFrSa1234567891011122314151617181920212223242526272829 >> [aria-label=\"close\"]").ClickAsync();
            await page.Locator(selector: "text=calendar May 2022SuMoTuWeThFrSa1234567891011122314151617181920212223242526272829 >> [aria-label=\"close\"]").ClickAsync();
            await page.Locator(selector: "button:has-text(\"Open AJAX content\")").ClickAsync();
            //the above will click on the calendar until it appears before it will perform the click operation, when the browser opens, the calendar is opened
            //..it will close the calender but it will have to click on the calender to ropen and close it again
        }

        [Test]
        public async Task TestNetwork()
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false,
            });
            var page = await browser.NewPageAsync();
            await page.GotoAsync(url: "http://www.eaapp.somee.com");
            var loginPage = new LoginPageUpgraded(page);
            await loginPage.ClickLogin();
            await loginPage.Login("admin", "password");

            //verifying the response is OK from API testing
            //await page.PauseAsync();
            // var waitRequest = page.WaitForRequestAsync("**/Employee"); //HOW TO WAIT FOR THE REQUEST
            //var waitResponse = page.WaitForResponseAsync("**/Employee"); //HOW TO WAIT FOR A RESPONSE WAY 1
            ////to get the response to be OK, change it tp waitforresponseasync()
            //await loginPage.ClickEmployeesList();
            //var getResponse = await waitResponse;
            var response = await page.RunAndWaitForResponseAsync(async () => //HOW TO WAIT FOR E RESPONSE WAY 2
            {
                await loginPage.ClickEmployeesList();
            }, x => x.Url.Contains("/Employee") && x.Status == 200); //this will give the same thing as the var waitResponse output
                                                                     //because the response is OK and it gives more details, an assertion can be done at this stage.
                                                                     //This also helps with API testing
            var isExist = await loginPage.IsEmployeesDetailDisplayed();
            Assert.IsTrue(isExist);
        }

        [Test]

        public async Task Flipkart()
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false,
            });
            var context = await browser.NewContextAsync();
            var page = await context.NewPageAsync();
            await page.GotoAsync(url: "https://www.flipkart.com/", new PageGotoOptions
            {
                WaitUntil = WaitUntilState.NetworkIdle
            });
            /*  await page.GotoAsync("https://www.flipkart.com/",new() 
              { 
                  WaitUntil = WaitUntilState.DOMContentLoaded 
              });*/ //modern use instead of waituntilstate
                    // await page.PauseAsync(); //used this to get the actual locator for the x button
                    //await page.Locator(selector: "text=x").ClickAsync(); //the x is the close button in the UI popup window, but the new version has no x, so comment it out
            await page.GetByRole(AriaRole.Button, new() { Name = "X" }).ClickAsync(); //this is to close the popup windown showing in the automated browser
            //await page.GetByText("?").ClickAsync();
            /*await page.Locator("span").Filter(new()
               {
                   HasTextString = "?"
               }).ClickAsync();*/
            /* var closeButton = page.GetByRole(AriaRole.Button,new() { Name = "X" });
             await closeButton.ClickAsync();*/
            /* var closeButton = page.GetByRole(AriaRole.Button,new() { Name = "X" });
             Console.WriteLine(await closeButton.CountAsync());*/
            //await page.Keyboard.PressAsync("Escape");
            await page.Locator(selector: "a", new PageLocatorOptions
            {
                HasTextString = "Login"
            }).ClickAsync();
            var request = await page.RunAndWaitForRequestAsync(async () =>
            {
                await page.Locator(selector: "text=X").ClickAsync();
            }, x => x.Url.Contains("googleads.g.doubleclick.net") && x.Method == "GET");
            //The url and method is copied from the summary of the page via omnibug when you click on the button/action in UI.
            // }, x => x.Url.Contains("googleads.g.doubleclick.net) && x.Status == 200);
            //}, x => x.Url.Contains("flipkart.com/account/login?ret=/account/login") && x.Method == "GET"); 
            /*var isExist = await loginPage.IsEmployeesDetailDisplayed();
            Assert.IsTrue(isExist);*/

        }
        [Test]

        public async Task Flipkart2()
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false,
            });
            var context = await browser.NewContextAsync();
            var page = await context.NewPageAsync();
            await page.GotoAsync(url: "https://www.flipkart.com/");
            // Close startup popup
            //await page.GetByRole(AriaRole.Button, new() { Name = "X" }).First.ClickAsync();
            // Click Login
            /* await page.Locator("a", new PageLocatorOptions
             {
                 HasTextString = "Login"
             }).ClickAsync();
             // Wait for analytics request while closing Login popup
            //The action you're performing is triggering a Google Ads / DoubleClick tracking request, not an Adobe Analytics request.
             var request = await page.RunAndWaitForRequestAsync(
                 async () =>
                 {
                     await page.GetByRole(AriaRole.Button, new() { Name = "X" })
                               .First
                               .ClickAsync();
                 },
                 req =>
                     req.Url.Contains("omtrdc") &&
                     req.Method == "GET"
             );*/

            //Many tutorials assume a site is using Adobe Analytics, but the site may have changed its implementation since the video was recorded.

            //From the URL you've shown, your Playwright code is successfully capturing analytics traffic—the only....
            //issue was that you were waiting for the wrong analytics endpoint. 
            //QA Automation lesson
            //There are two different things here:Adobe Analytics
            //Typical URLs:
            //*.omtrdc.net
            //metrics.adobe.com
            //b / ss /
            //Google Ads / DoubleClick
            //Typical URLs:
            //googleads.g.doubleclick.net
            //googleadservices.com
            //doubleclick.net
            //hence Your captured URL is clearly in the second category.
            /* page.Request += (_, request) =>
             {
                 Console.WriteLine(request.Url);
             };*/
            /*  var request = await page.RunAndWaitForRequestAsync(async () =>
               {
                   await page.GetByRole(AriaRole.Link, new() { Name = "Login", Exact = true }).ClickAsync();
               }, req => req.Url.Contains("googleads.g.doubleclick.net") && req.Method == "GET");*/
            // Open login popup
            await page.GetByRole(
                AriaRole.Link,
                new() { Name = "Login", Exact = true }
            ).ClickAsync();

            // Wait for popup
            await page.Locator("text=Request OTP")
                      .WaitForAsync();

            // Capture request when closing popup
            var request = await page.RunAndWaitForRequestAsync(
                async () =>
                {
                    await page.Keyboard.PressAsync("Escape");
                },
                req => req.Url.Contains("googleads.g.doubleclick.net")
            );
        }
        [Test]
        public async Task DiscoverFlipkartAnalyticsTriggerStepByStep()
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false,
                SlowMo = 500
            });

            var context = await browser.NewContextAsync();
            var page = await context.NewPageAsync();

            page.Request += (_, request) =>
            {
                Console.WriteLine("--------------------------------------------------");
                Console.WriteLine($"METHOD: {request.Method}");
                Console.WriteLine($"URL: {request.Url}");
            };

            await page.GotoAsync("https://www.flipkart.com/", new PageGotoOptions
            {
                WaitUntil = WaitUntilState.DOMContentLoaded
            });

            await page.WaitForTimeoutAsync(4000);

            // ACTION 1
            Console.WriteLine("===== ACTION 1: CLICK LOGIN =====");
            // await page.PauseAsync();
            await page.GetByRole(AriaRole.Link, new() { Name = "Login", Exact = true }).ClickAsync();
            await page.WaitForTimeoutAsync(5000);

            // ACTION 2
            Console.WriteLine("===== ACTION 2: TYPE INTO LOGIN TEXTBOX =====");
            await page.GetByPlaceholder("Enter Email/Mobile number").FillAsync("9876543210");
            await page.WaitForTimeoutAsync(5000);

            // ACTION 3
            Console.WriteLine("===== ACTION 3: CLOSE POPUP WITH ESC =====");
            await page.Keyboard.PressAsync("Escape");
            await page.WaitForTimeoutAsync(5000);
        }

        [Test]
        public async Task Flipkart_LoginAnalytics2()
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false
            });

            var context = await browser.NewContextAsync();
            var page = await context.NewPageAsync();

            await page.GotoAsync("https://www.flipkart.com/", new PageGotoOptions
            {
                WaitUntil = WaitUntilState.DOMContentLoaded
            });

            await page.WaitForTimeoutAsync(3000);

            var loginModalInput = page.GetByPlaceholder("Enter Email/Mobile number");

            if (await loginModalInput.IsVisibleAsync())
            {
                Console.WriteLine("Popup already open - Login click is blocked by modal.");
                Assert.Pass("Popup already open on page load, so Login click test is not applicable in this run.");
                return;
            }

            var request = await page.RunAndWaitForRequestAsync(
                async () =>
                {
                    await page.GetByRole(AriaRole.Link, new() { Name = "Login", Exact = true }).First.ClickAsync();
                },
                req => req.Url.Contains("googleads.g.doubleclick.net") && req.Method == "GET",
                new PageRunAndWaitForRequestOptions
                {
                    Timeout = 10000
                });

            Console.WriteLine($"Analytics URL: {request.Url}");
        }
        [Test]
        public async Task TestingAnalytics()
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false,
            });
            var context = await browser.NewContextAsync();
            var page = await context.NewPageAsync();
            await page.GotoAsync(url: "https://www.practicesoftwaretesting.com/", new PageGotoOptions
            {
                WaitUntil = WaitUntilState.NetworkIdle
            });
            //await page.PauseAsync();
            //await page.Locator("Locator("[data-test = \"product-01KVRNJMXSOSKPGH4DRHJKPD8H\"]");
            /* await page.Locator("[data-test=\"product-01KVRNJMXSOSKPGH4DRHJKPD8H\"]").ClickAsync();
             var request = await page.RunAndWaitForRequestAsync(async () =>
             {
                 await page.Locator(selector: "text=X").ClickAsync();
             }, x => x.Url.Contains("region1.google-analytics.com/g") && x.Method == "POST");*/
            //var productCard = page.Locator("[data-test=\"product-01KVRNJMXSOSKPGH4DRHJKPD8H\"]");
            var productCard = page.GetByRole(AriaRole.Img, new() { Name = "Combination Pliers" });

            var request = await page.RunAndWaitForRequestAsync(
                async () =>
                {
                    await productCard.ClickAsync();
                },
                req => req.Url.Contains("region1.google-analytics.com/g") &&
                       req.Method == "POST");
            // to decode the url that contains product and ID, c# can do it 
            var returnData = HttpUtility.UrlDecode(request.Url);
            //NUnit asssertion
            /* Assert.That(request, Is.Not.Null);
             Assert.That(request.Method, Is.EqualTo("POST"));
             Assert.That(returnData, Does.Contain("en=page_view"));
             Assert.That(returnData, Does.Contain("/product/"));*/
            //downloaded the fluent assertion package for the assertion to be more natural
            request.Should().NotBeNull();
            request.Method.Should().Be("POST");
            returnData.Should().Contain("region1.google-analytics.com/g");
            returnData.Should().Contain("en=page_view");
            returnData.Should().Contain("/product/");


        }
    }
}
